online_clinic/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('index_page', views.index_page, name='index_page'),
    path('doctors', views.doctors_page, name='doctors'),
    path('price', views.price_page, name='price'),
    path('contacts', views.contacts_page, name='contacts'),
    path('login', views.login_page, name='login'),
    path('register', views.register_page, name='register'),
    path('profile', views.profile_page, name='profile'),
    path('logout', views.logout_view, name='logout_view'),
    path('zapic', views.zapic_page, name='zapic'),
]

online_clinic/online_clinic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls'))
]

online_clinic/main/models.py
from django.db import models

class Divisions(models.Model):
    name = models.CharField(max_length=100, verbose_name='Подразделения')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f"{self.name}: {self.description}"

class Patient(models.Model):
    data_of_birth = models.DateField(verbose_name='Дата Рождения')
    divisions = models.ForeignKey(Divisions, on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return f"{self.data_of_birth}: {self.divisions}"

online_clinic/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.models import User

# Create your views here.
def index_page(request):
    print('request is accepted')

    context = {
        'username': 'Test',

        }
    return render(request, 'main/index.html', context)

def doctors_page(request):
    return render(request, 'main/doctors.html', {} )

def price_page(request):
    return render(request, 'main/price.html', {} )

def contacts_page(request):
    return render(request, 'main/contacts.html', {} )

def login_page(request):
    if request.method == "POST":
        username = request.POST.get("username", None)
        password = request.POST.get("password", None)
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect(reverse("main:profile"))

        return render(request, 'main/login.html', {"error": "Неверный Логин/Пароль"})
    return render(request, 'main/login.html', {})

def register_page(request):
    if request.method == "POST":
        try:
            username = request.POST.get('username', None)
            password = request.POST.get('password', None)
            email = request.POST.get('email', None)
            first_name = request.POST.get('first_name', None)
            last_name = request.POST.get('last_name', None)
            user = User.objects.create_user(
                username=username,
                password=password,
                email=email,
                first_name=first_name,
                last_name=last_name,
            )
            return redirect(reverse("main:login"))
        except Exception as exc:
            print('При создании профиля произошла ошибка', request.POST, exc)
            error = {
                "error_code": exc,
                "message": "Проверьте корректность введенных данных"
            }
            return render(request, "main/register.html", {"error": error})

    return render(request, "main/register.html", {})

def profile_page(request):
    if request.user.is_authenticated:
        return render(request, "main/profile.html", {})
    return redirect(reverse('main:login'))

def logout_view(request):
    logout(request)
    return redirect(reverse("main:index_page"))

def zapic_page(request):
    if request.method == "POST":
        try:
            name = request.POST.get('name', None)
            otdel = request.POST.get('otdel', None)
            phone = request.POST.get('phone', None)
            user = User.objects.create_user(
                name=name,
                otdel=otdel,
                phone=phone,
            )
            return redirect(reverse("main:zapic"))
        except Exception as exc:
            print('При записи на прием произошла ошибка', request.POST, exc)
            error = {
                "error_code": exc,
                "message": "Проверьте корректность введенных данных"
            }
            return render(request, "main/zapic.html", {"error": error})

    return render(request, "main/zapic.html", {})

online_clinic/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <style>
   .leftimg {
    float:left; /* Выравнивание по левому краю */
    margin: 25px 0px 0px 0; /* Отступы вокруг картинки */
   }
  </style>

  <a class="center-block text-center" href="{% url 'main:index_page'%}">
      <img src="{% static 'main/iconic.png' %}" width="120" height="110" alt="icon" title="diqten" class="leftimg">
  </a>
  <header>
    <div class="container"
        <div class="row">
            <div class="phones text-center col-sm-12"><p class="time">Звоните сегодня с 08:00 до 20:00</p>
                <p><a href="tel:+77055360303"><span class="glyphicon glyphicon-earphone" aria-hidden="true"> </span> +7 (775) 609-34-45</a></p>
                <p><a href="tel:+77777070707"><span class="glyphicon glyphicon-earphone" aria-hidden="true"> </span> +7 (777) 707-07-07</a></p>
                <p><a href="tel:+77055555505"><span class="glyphicon glyphicon-earphone" aria-hidden="true"> </span> +7 (705) 555-55-05</a></p>
                <p style="display:none"><a href="tel:+77172660303"><span class="glyphicon glyphicon-earphone" aria-hidden="true"> </span> +7 (7172) 66-03-03</a></p>
            </div>
        </div>
    </div>
  </header>
</div>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body class="container-fluid">
    {% include "main/header.html" %}
    {% block body %}

    {% endblock %}
    {% include "main/footer.html" %}
</body>
</html>

online_clinic/main/templates/main/contacts.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} CONTACTS PAGE {% endblock %}

{% block body %}
    <h2> CONTACTS </h2>


{% endblock %}

online_clinic/main/templates/main/doctors.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} DOCTORS {% endblock %}

{% block body %}
<hr class="separator">
<style>
 .separator {
   height: 7px;
   background: #0DCAF0;
   margin: 25px 0;
   box-shadow: 0px 0px 5px 3px rgba(0,205,255,1);
}
</style>
    <h1 class="text-center"> ВРАЧИ </h1>
<style>
.team-boxed {
  color:#0DCAF0;
  background-color:#eef4f7;
}

.team-boxed p {
  color:#7d8285;
}

.team-boxed h2 {
  font-weight:bold;
  margin-bottom:40px;
  padding-top:40px;
  color:inherit;
}

@media (max-width:767px) {
  .team-boxed h2 {
    margin-bottom:25px;
    padding-top:25px;
    font-size:24px;
  }
}

.team-boxed .intro {
  font-size:16px;
  max-width:500px;
  margin:0 auto;
}

.team-boxed .intro p {
  margin-bottom:0;
}

.team-boxed .people {
  padding:50px 0;
}

.team-boxed .item {
  text-align:center;
}

.team-boxed .item .box {
  text-align:center;
  padding:30px;
  background-color:#fff;
  margin-bottom:30px;
}

.team-boxed .item .name {
  font-weight:bold;
  margin-top:28px;
  margin-bottom:8px;
  color:#0DCAF0;
}

.team-boxed .item .title {
  text-transform:uppercase;
  font-weight:bold;
  color:#d0d0d0;
  letter-spacing:2px;
  font-size:13px;
}

.team-boxed .item .description {
  font-size:15px;
  margin-top:15px;
  margin-bottom:20px;
}

.team-boxed .item img {
  max-width:160px;
}

.team-boxed .social {
  font-size:18px;
  color:#0DCAF0;
}

.team-boxed .social a {
  color:inherit;
  margin:0 10px;
  display:inline-block;
  opacity:0.7;
}

.team-boxed .social a:hover {
  opacity:1;
}

                </style>
<hr class="separator">
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Untitled</title>



</head>

<body>
    <div class="team-boxed">
        <div class="container">
            <div class="row people">
                <div class="col-md-6 col-lg-4 item">
                    <div class="box"><img class="rounded-circle" src="/static/main/sergei.jpg">
                        <h3 class="name">Cергей Тестович</h3>
                        <p class="title">Кардиолог</p>
                        <p class="description"> Получил большой опыт в зарубежных клиниках. Использует навыки, знания и опыт в предупреждении и лечении заболеваний. </p>
                        <body>
                            <a href="{% url 'main:zapic'%}" class="btn btn-info">Записаться</a>
                        </body>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 item">
                    <div class="box"><img class="rounded-circle" src="/static/main/zhanel.jpeg">
                        <h3 class="name">Жанель Шериазданова</h3>
                        <p class="title">Дерматолог</p>
                        <p class="description">врач высшей категории, кандидат медицинских наук,имеет несколько специализаций, что позволяет распознать заболевание и поставить точный диагноз.</p>
                        <body>
                            <a href="{% url 'main:zapic'%}" class="btn btn-info">Записаться</a>
                        </body>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 item">
                    <div class="box"><img class="rounded-circle" src="/static/main/asel.jpg">
                        <h3 class="name">Асель Мамаева</h3>
                        <p class="title">Эндрокринолог</p>
                        <p class="description">имеет несколько специализаций, что позволяет распознать заболевание и поставить точный диагноз </p>
                        <body>
                            <a href="{% url 'main:zapic'%}" class="btn btn-info">Записаться</a>
                        </body>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

{% endblock %}

online_clinic/main/templates/main/footer.html
<footer class="footer font-small teal pt-5">
  <div class="container-fluid text-center">
    <div class="row mx-auto text-center">
      <hr class="clearfix w-100 d-md-none pb-3">
      <div class="col-md-12 mb-md-0 mb-3">
        <h4 class="text-uppercase font-weight-bold">МЕЖДУНАРОДНЫЙ МЕДИЦИНСКИЙ ЦЕНТР DIQTEN CLINIC</h4>
          <p>Медицинский центр «Diqten Clinic» Астана является филиалом международной корпорации «INClinic» – безусловного лидера по восстановлению мужской потенции. Методики «Diqten Clinic» успешно внедрены по всему миру, доказательство тому – более 3 миллионов благодарных пациентов</p>
      </div>
    </div>
  </div>
  <div class="footer-copyright text-center py-3">© 2022 Copyright:
    <a href="/"> diqtenclinic.pythonanywhere.com</a>
  </div>
</footer>

online_clinic/main/templates/main/header.html
<style></style>
<nav class="navbar navbar-expand-lg navbar-light bg-info static-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main:index_page'%}"><b>DiqtenClinic</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class=" collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto ">
        <li class="nav-item">
          <a class="nav-link mx-2 active" aria-current="page" href="{% url 'main:index_page'%}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="{% url 'main:doctors'%}">Врачи</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="{% url 'main:price'%}">Цены</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="{% url 'main:zapic'%}">Записаться</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link mx-2 dropdown-toggle" href="{% url 'main:profile'%}" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Профиль
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'main:profile'%}">Мой Профиль</a></li>
            <li><a class="dropdown-item" href="{% url 'main:register'%}">Зарегистрироваться</a></li>
            <li><a class="dropdown-item" href="{% url 'main:login'%}">Войти</a></li>
            <li><a class="dropdown-item" href="{% url 'main:logout_view'%}">Выйти</a></li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto d-none d-lg-inline-flex">
        <li class="nav-item mx-2">
          <a class="nav-link text-dark h5" href="" target="blank"><i class="fab fa-google-plus-square"></i></a>
        </li>
        <li class="nav-item mx-2">
          <a class="nav-link text-dark h5" href="" target="blank"><i class="fab fa-twitter"></i></a>
        </li>
        <li class="nav-item mx-2">
          <a class="nav-link text-dark h5" href="" target="blank"><i class="fab fa-facebook-square"></i></a>
        </li>
      </ul>
    </div>
  </div>
</nav>

online_clinic/main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} Index Page Title {% endblock %}

{% block body %}
<hr class="separator">
  <style type="text/css">
   IMG.figg {
    float: right; /* Обтекание картинки по левому краю */
    padding-right: 10px; /* Отступ слева */
    padding-bottom: 10px; /* Отступ снизу */
   }
  </style>
<div class="row">
        <div class="col-sm-6">
            <img src="/static/main/Corona-740x200.jpg" width="740" height="200" class="figg"  >
        </div>
        <div class="col-sm-5 my-auto">
            <p class="text-center">
            <h4>Коронавирусная инфекция</h4> COVID-19 воздействует на различные группы людей в разной степени. У большинства инфицированных болезнь протекает в легкой или средней форме тяжести, и им не требуется госпитализация.
            <p>Если у вас наблюдаются симптомы тяжелой формы заболевания, незамедлительно обратитесь за медицинской помощью. Прежде чем посещать клинику или больницу, позвоните и предупредите о своем визитe.
        </div>
</div>
<hr class="separator">
<style>
 .separator {
   height: 7px;
   background: #0DCAF0;
   margin: 50px 0;
   box-shadow: 0px 0px 5px 3px rgba(0,205,255,1);
}
</style>
  <style type="text/css">
   IMG.fig {
    float: right; /* Обтекание картинки по левому краю */
    padding-left: 10px; /* Отступ слева */
    padding-bottom: 10px; /* Отступ снизу */
   }
  </style>
<div class="col-sm-12">
    <h3>Красивая версия вашего здоровья</h3>
    <img src="{% static 'main/meds.jpg' %}" width="250" height="250" class="fig">
    <div class="col-sm-12"
        <p class="text-center"
        <p><b>Diqten Clinic</b> готова порадовать Вас полным комплексом услуг в области косметологии, стоматологии, пластической хирургии и anti-age медицине.
        В основу работы Медцентра на Победителей 135 в Лебяжем заложены высокие стандарты обслуживания, соответствующие лучшим клиникам и медучреждениям Нур-Султана.
        Выдающиеся результаты достигаются благодаря усилиям высококвалифицированных специалистов, новейшему европейскому оборудованию, а также соблюдению основных принципов лечения:</p>

    <p>- Комплексный подход к работе с каждым пациентом.</p>
    <p>- Индивидуально разработанные схемы лечения и восстановления.</p>
    <p>- Строгое соответствие мировым лечебным стандартам.</p>
    <p>- Высокая ответственность за результат.</p>
</div>

<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8">
  <title>Кнопка</title>
  <style>
   .btn {
    display: inline-block; /* Строчно-блочный элемент */
    background: #1C759D; /* Синий цвет фона */
    color: #fff; /* Белый цвет текста */
    padding: 1rem 1.5rem; /* Поля вокруг текста */
    text-decoration: none; /* Убираем подчёркивание */
    border-radius: 3px; /* Скругляем уголки */
    width:100%
   }
  </style>
 </head>
<div class="text-center"
 <body>
  <a href="{% url 'main:zapic'%}" class="btn">Записаться на прием</a>
 </body>
</html>
<hr class="separator"
<div class="card">
<style>
.team-boxed {
  color:#0DCAF0;
  background-color:#eef4f7;
}

.team-boxed p {
  color:#7d8285;
}

.team-boxed h2 {
  font-weight:bold;
  margin-bottom:40px;
  padding-top:40px;
  color:inherit;
}

@media (max-width:767px) {
  .team-boxed h2 {
    margin-bottom:25px;
    padding-top:25px;
    font-size:24px;
  }
}

.team-boxed .intro {
  font-size:16px;
  max-width:500px;
  margin:0 auto;
}

.team-boxed .intro p {
  margin-bottom:0;
}

.team-boxed .people {
  padding:50px 0;
}

.team-boxed .item {
  text-align:center;
}

.team-boxed .item .box {
  text-align:center;
  padding:30px;
  background-color:#fff;
  margin-bottom:30px;
}

.team-boxed .item .name {
  font-weight:bold;
  margin-top:28px;
  margin-bottom:8px;
  color:#0DCAF0;
}

.team-boxed .item .title {
  text-transform:uppercase;
  font-weight:bold;
  color:#d0d0d0;
  letter-spacing:2px;
  font-size:13px;
}

.team-boxed .item .description {
  font-size:15px;
  margin-top:15px;
  margin-bottom:20px;
}

.team-boxed .item img {
  max-width:160px;
}

.team-boxed .social {
  font-size:18px;
  color:#0DCAF0;
}

.team-boxed .social a {
  color:inherit;
  margin:0 10px;
  display:inline-block;
  opacity:0.7;
}

.team-boxed .social a:hover {
  opacity:1;
}

                </style>
    <div class="team-boxed"
            <div class="row people">
                <div class="col-md-6 col-lg-12 item">
                    <div class="box"><img class="rounded-circle" src="/static/main/sergei.jpg">
                        <h3 class="name">Cергей Тестович</h3>
                        <p class="title">Кардиолог</p>
                        <p class="description"> Получил большой опыт в зарубежных клиниках. Использует навыки, знания и опыт в предупреждении и лечении заболеваний. Руководитель отдела интервенционной кардиологии и радиологии в "Национальном Научном Кардиохирургическом Центре". Отличник здравоохранения Республики Казахстан. Автор более 80 научных публикаций по проблемам кардиохирургии, интервенционной кардиологии, эхокардиографии, двух подтвержденных изобретений и 16 актов внедрения.  </p>

                        <body>
                            <a href="{% url 'main:zapic'%}" class="btn btn-info">Записаться</a>
                        </body>
                    </div>
                </div>
<hr class="separator"
{% endblock %}

online_clinic/main/templates/main/login.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} Index Page Title {% endblock %}

{% block body %}
<hr class="separator">
<style>
 .separator {
   height: 7px;
   background: #0DCAF0;
   margin: 15px 0;
   box-shadow: 0px 0px 5px 3px rgba(0,205,255,1);
}
</style>
        <div class="row">
            <div class="col-sm-12 text-center">
                <h3>Вход</h3>
            </div>
        </div>
<hr class="separator">
    <div class="row">
        <div class="col-sm-2 mx-auto">
            <form method="post" class="form mx-auto" >
                {% if error %}
                    <p class="text-danger">{{error}}</p>
                {% endif %}
                <div class="input-group">
                    {% csrf_token %}
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    <input type="text" class="form-control w-25" placeholder="Имя пользователя" name="username" required>
                </div>
                <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <input type="password" class="form-control w-25" placeholder="Пароль" name="password" required>
                </div>
                <input type="submit" class="btn btn-info col-sm-12 mx-auto" value="Войти">
            </form>
        </div>
    </div>

{% endblock %}

online_clinic/main/templates/main/price.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} PRICE PAGE {% endblock %}

{% block body %}
<hr class="separator">
<h1 class="text-center">ЦЕНЫ</h1>
<hr class="separator">
<style>
 .separator {
   height: 7px;
   background: #0DCAF0;
   margin: 15px 0;
   box-shadow: 0px 0px 5px 3px rgba(0,205,255,1);
}
</style>
<style>
.pricingTable{
 padding: 25px 0;
 text-align: center;
 position: relative;
}
.pricingTable:hover{ background: #f7fcfb; }
.pricingTable:before,
.pricingTable:after{
 content: "";
 display: block;
 width: 100%;
 height: 70px;
 border: 2px solid #1C759D;
 position: absolute;
 left: 0;
 transition: all 0.3s ease 0s;
}
.pricingTable:before{
 top: 0;
 border-bottom: none;
}
.pricingTable:after{
 bottom: 0;
 border-top: none;
}
.pricingTable:hover:before,
.pricingTable:hover:after{
 height: 50%;
}
.pricingTable .title{
 font-size: 25px;
 font-weight: 700;
 color: #1C759D;
 text-transform: uppercase;
 margin: 0 0 40px 0;
}
.pricingTable .price-value{
 padding: 20px 0;
 background: #0DCAF0;
 font-size: 30px;
 color: #fff;
 margin-bottom: 20px;
 border-top: 2px solid #108bd7;
 border-bottom: 2px solid #108bd7;
}
.pricingTable .pricing-content{
 list-style: none;
 padding: 0;
 margin: 0 0 20px 0;
}
.pricingTable .pricing-content li{
 font-size: 15px;
 color: #898384;
 line-height: 50px;
}
.pricingTable .pricingTable-signup{
 display: inline-block;
 padding: 8px 20px;
 font-size: 15px;
 font-weight: 600;
 color: #898384;
 text-transform: uppercase;
 z-index: 1;
 position: relative;
 transition: all 0.3s ease 0s;
}
.pricingTable .pricingTable-signup:before,
.pricingTable .pricingTable-signup:after{
 content: "";
 display: block;
 width: 100%;
 height: 10px;
 border: 2px solid #108bd7;
 position: absolute;
 left: 0;
 z-index: 2;
 transition: all 0.3s ease 0s;
}
.pricingTable .pricingTable-signup:before{
 top: 0;
 border-bottom: none;
}
.pricingTable .pricingTable-signup:after{
 bottom: 0;
 border-top: none;
}
.pricingTable .pricingTable-signup:hover:before,
.pricingTable .pricingTable-signup:hover:after{
 height: 50%;
}
@media only screen and (max-width: 990px){
 .pricingTable{ margin-bottom: 30px; }
}
</style>

<div class="container"><div class="row">

 <div class="col-md-3 col-sm-3">
    <div class="pricingTable">
        <h3 class="title">Кардиолгия</h3>
        <div class="price-value">13.500 тг</div>
            <ul class="pricing-content">
                <li>Физикальное обследование</li>
                <li>Измерение артериального давления</li>
                <li>Консультация доктора</li>
                <li>Услуги по забору крови</li>
            </ul>
            <a href="{% url 'main:zapic'%}" class="pricingTable-signup">Записаться</a>
        </div>
    </div>

 <div class="col-md-3 col-sm-3">
 <div class="pricingTable">
 <h3 class="title">Невропатолгия</h3>
 <div class="price-value">12.250 тг</div>
 <ul class="pricing-content">
 <li>Сбор анамнеза</li>
 <li>Проверка состояния нервов</li>
 <li>Проверка координации движений</li>
 <li>Консультация доктора</li>
 </ul>
 <a href="{% url 'main:zapic'%}" class="pricingTable-signup">Записаться</a>
 </div>
 </div>

 <div class="col-md-3 col-sm-3">
 <div class="pricingTable">
 <h3 class="title">Дерматология</h3>
 <div class="price-value">6.800 тг</div>
 <ul class="pricing-content">
 <li>Физикальный осмотр</li>
 <li>Консультация доктора</li>
 <li>Измерение артериального давления</li>
 <li>Сбор анализа</li>
 </ul>
 <a href="{% url 'main:zapic'%}" class="pricingTable-signup">Записаться</a>
 </div>
 </div>

 <div class="col-md-3 col-sm-3">
 <div class="pricingTable">
 <h3 class="title">Эндокринолгия</h3>
 <div class="price-value">6.500 тг</div>
 <ul class="pricing-content">
 <li>Сбор анамнеза</li>
 <li>Определение индекса массы тела</li>
 <li>Физикальный осмотр пациента</li>
 <li>Консультация доктора</li>
 </ul>
 <a href="{% url 'main:zapic'%}" class="pricingTable-signup">Записаться</a>
 </div>
 </div>

</div></div>

{% endblock %}

online_clinic/main/templates/main/profile.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} Profile Page Title {% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h2>ФИ: {{ user.last_name }} {{ user.first_name }}</h2>
            <p>Почта: {{ user.email }}</p>
            <p>Пароль: {{ user.password }}</p>
        </div>
    </div>

{% endblock %}

online_clinic/main/templates/main/register.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} Index Page Title {% endblock %}

{% block body %}
<hr class="separator">
<style>
 .separator {
   height: 7px;
   background: #0DCAF0;
   margin: 15px 0;
   box-shadow: 0px 0px 5px 3px rgba(0,205,255,1);
}
</style>
        <div class="row">
            <div class="col-sm-12 text-center">
                <h3>Регистрация</h3>
            </div>
        </div>
<hr class="separator">
    <div class="row">
        <div class="col-sm-2 mx-auto">
            <form method="post" class="form mx-auto">
                {% if error %}
                    <p class="text-danger">{{ error }}</p>
                {% endif %}
                <div class="input-group">
                    {% csrf_token %}
                    <input type="text" class="form-control w-25" placeholder="Имя пользователя" name="username" required>
                </div>
                <div class="input-group">
                    <input type="password" class="form-control w-25" placeholder="Пароль" name="password" required>
                </div>
                <div class="input-group">
                    <input type="text" class="form-control w-25" placeholder="Почта" name="email" required>
                </div>
                <div class="input-group">
                    <input type="text" class="form-control w-25" placeholder="Фамилия" name="last_name" required>
                </div>
                <div class="input-group">
                    <input type="text" class="form-control w-25" placeholder="Имя" name="first_name" required>
                </div>

                <input type="submit" class="btn btn-info col-sm-12 mx-auto" value="Зарегистрироваться">
            </form>
        </div>
    </div>

{% endblock %}